version: "3"
services:
  web:
    build: .
    environment:
      - PORT=3000
      - ENV_NAME=local
      - ELASTICSEARCH_BASEURL=http://elasticsearch:9200
      - ELASTICSEARCH_REFRESH_INTERVAL=1s
      - ELASTICSEARCH_INTELLIGENCE_INDEX=lineup
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - ./server:/usr/src/app/server
      - ./test:/usr/src/app/test
      - ./package.json:/usr/src/app/package.json
    ports:
      - "3000:3000"
    command: npm start

  wait:
      image: waisbrot/wait
      links:
        - elasticsearch
      environment:
        - TARGETS=elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    ports:
      - "9200:9200"
    expose:
      - "9200"
